
project_id = "qjoxiowuiiupbvqlssgk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://id-preview--bf5f0070-40f8-4760-bbe1-41e5ac0dce78.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_signup = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions]
verify_jwt = true

[functions.get-community-page-data]
verify_jwt = false

[functions.get-saved-posts]
verify_jwt = true

[functions.save-post]
verify_jwt = true

[functions.get-community-post-detail]
verify_jwt = false

[functions.create-community-post]
verify_jwt = true

[functions.moderate-community-post]
verify_jwt = true

[functions.get-review-by-slug]
verify_jwt = false

[functions.cast-poll-vote]
verify_jwt = true

[functions.reward-content]
verify_jwt = true

[functions.admin-get-content-queue]
verify_jwt = false

[functions.admin-manage-publication]
verify_jwt = false
