
project_id = "qjoxiowuiiupbvqlssgk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge-runtime]
enabled = true
port = 54328
ip_version = "ipv4"

[functions.get-homepage-feed]
verify_jwt = false

[functions.get-acervo-data]
verify_jwt = false

[functions.get-community-page-data]
verify_jwt = false

[functions.get-community-post-detail]
verify_jwt = false

[functions.get-review-by-slug]
verify_jwt = false

[functions.save-post]
verify_jwt = false

[functions.get-saved-posts]
verify_jwt = false

[functions.reward-content]
verify_jwt = false

[functions.admin-assign-roles]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = false

[functions.admin-get-content-queue]
verify_jwt = false

[functions.admin-user-analytics]
verify_jwt = false

[functions.admin-content-analytics]
verify_jwt = false

[functions.admin-manage-publication]
verify_jwt = false

[functions.admin-bulk-content-actions]
verify_jwt = false
